CXX = g++
CXXFLAGS = -std=c++17 -Iinclude -Wall -Wextra
SRC_DIR = src
INC_DIR = include
OBJ_DIR = obj

OBJS = $(OBJ_DIR)/main.o $(OBJ_DIR)/Grammatic.o

all: main

main: $(OBJS)
	$(CXX) $(CXXFLAGS) -o main $(OBJS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	mkdir -p $(OBJ_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJ_DIR) main
